**Lab Manual: K-Nearest Neighbors (KNN) Classifier Implementation**

**Objective:** Implement a K-Nearest Neighbors (KNN) classifier from scratch using Python and understand its working.

**Prerequisites:**
- Basic understanding of Python programming.
- Familiarity with basic machine learning concepts.

**Introduction:**


The k-Nearest Neighbors (K-NN) algorithm is a simple yet effective machine learning method used for classification and regression tasks. In this lab, we will dive into the implementation of the K-NN classifier. By the end of this lab, you'll have a clear understanding of how KNN works and how to implement it from scratch using Python.

**Lab Steps:**

1. **Setting Up the Environment:**
   - Open your Python environment (Jupyter Notebook, Google Colab, etc.).
   - Import the required libraries: NumPy for numerical computations and Matplotlib for visualization.

In [3]:
import numpy as np
import matplotlib.pyplot as plt
# Import necessary libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

2. **Generating Synthetic Data:**
   To begin, generate synthetic data with two classes for classification.

In [4]:
# Load the Iris dataset
iris = load_iris()
X = iris.data #(150 rows, 4 features)
y = iris.target #(3 clas s)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

3. **Implementing the kNN Classifier:**
   Create a class named `KNNClassifier` to implement the kNN algorithm.

In [5]:
class KNNClassifier:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def predict(self, X_test):
        distances = np.sqrt(np.sum((X_test[:, np.newaxis] - self.X_train)**2, axis=2))
        nearest_indices = np.argsort(distances, axis=1)[:, :self.k]
        nearest_labels = self.y_train[nearest_indices]
        # predicted_labels = np.apply_along_axis(lambda x: np.bincount(x).argmax(), axis=1, arr=nearest_labels)
        # predicted_labels = np.apply_along_axis(np.bincount, axis=1, arr=nearest_labels).argmax(axis=1)
        predicted_labels = np.zeros(nearest_labels.shape[0], dtype=int)
        for i in range(nearest_labels.shape[0]):
            unique, counts = np.unique(nearest_labels[i], return_counts=True)
            predicted_labels[i] = unique[np.argmax(counts)]

        return predicted_labels

4. **Understanding the kNN Algorithm:**
   kNN works by finding the k nearest data points to a given input and classifying based on majority votes.


5. **Training and Testing:**
   Instantiate the `KNNClassifier`, fit it with the training data, and test it using new data.

In [6]:
model = KNNClassifier(k=5)
model.fit(X_train, y_train)

# new_samples = 20
# new_data = np.random.randn(new_samples, 2) + [3.5, 3.5]
predictions = model.predict(X_test)
print(predictions)


# Calculate accuracy
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Accuracy: 100.00%


In [7]:
X_test[1]

array([5.7, 3.8, 1.7, 0.3])

In [8]:
# Initialize the kNN classifier
k = 5
knn_classifier = KNeighborsClassifier(n_neighbors=k)

# Train the classifier on the training data
knn_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = knn_classifier.predict(X_test)
print(y_pred)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")


[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Accuracy: 100.00%
